import SessionProvider from "@/components/SessionProvider";
import { auth } from "@/lib/auth";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";
// import Script from "next/script";
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const fontHeading = IBM_Plex_Mono({
  weight: "700",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

const fontBody = IBM_Plex_Mono({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      {/* <Script src="https://unpkg.com/react-scan/dist/auto.global.js"></Script> */}
      <body
        className={cn(
          `antialiased flex flex-col min-h-screen`,
          fontHeading.variable,
          fontBody.variable,
        )}
      >
        <NuqsAdapter>
          <SessionProvider session={session}>{children}</SessionProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
